apiVersion: v1
kind: Secret
metadata: 
   name: cdw-access
type: Opaque
data:
   CDW_HOST: VkhBQ0RXQTAxLnZoYS5tZWQudmEuZ292
   CDW_USER: VkhBTUFTVEVSXEJJU0xfT0hSU19BcHA=
   CDW_PASSWORD: VyFlNio3SGQzS2EkRSQ1eSFpSjJNKjhralkqOQ==
   KRB_USER: VkhBTUFTVEVSXEJJU0xfT0hSU19BcHA=
   KRB_PASSWORD: VyFlNio3SGQzS2EkRSQ1eSFpSjJNKjhralkqOQ==
