#!/usr/bin/env bash

set -e

# Sleep to run after MySQL container start
# bash -xc 'until nc mysql 3306; do echo -n . ; sleep 1; done'

# sleep 3

# printf '\n\nRunning updateDatabase scripts...'
# php /var/www/html/LEAF_Nexus/scripts/updateDatabase.php
# php /var/www/html/LEAF_Request_Portal/scripts/updateDatabase.php

# printf '\n\nRunning composer install...'
# cd /var/www/html/test && composer install

# printf '\n\nRunning composer install...'
# cd /var/www/html/test/prepend && composer install

echo "root=$SMTP_ROOT" >> /etc/ssmtp/ssmtp.conf
echo "nmailhub=$LEAF_MAIL_HUB" >> /etc/ssmtp/ssmtp.conf
# /bin/bash /etc/init.d/krb_wrangler.sh &

if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
