apiVersion: v1
kind: Secret
metadata: 
   name: krb-access
type: Opaque
data:
   KRB_DOMAIN: dmhhLm1lZC52YS5nb3Y=
   KRB_USER: QklTTF9PSFJTX0FwcA==
   KRB_PASSWORD: VyFlNio3SGQzS2EkRSQ1eSFpSjJNKjhralkqOQ==

